# Generated by Django 3.0.4 on 2020-03-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspiration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poem',
            name='created_date',
        ),
        migrations.AddField(
            model_name='poem',
            name='day',
            field=models.DateField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='poem',
            name='month',
            field=models.DateField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='poem',
            name='year',
            field=models.DateField(blank=True, max_length=4, null=True),
        ),
    ]
