# Generated by Django 3.0.4 on 2020-05-19 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inspiration', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentpoem',
            name='title_poem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title_poem_comment', to='inspiration.Poem'),
        ),
        migrations.AlterField(
            model_name='commentpoem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='poem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/poem'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
