# Generated by Django 3.0.4 on 2020-05-20 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspiration', '0006_auto_20200520_0125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentpoem',
            name='title_poem',
        ),
        migrations.AddField(
            model_name='commentpoem',
            name='id_poem',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='poem_comment', to='inspiration.Poem'),
        ),
    ]
